<?php
    /*
    * The main execution for the subsidy package is hosted here.
    * You can just call `generate_all_subsidies` informing a schema
    * generated by the `utils.patient_therapy_to_schema` or `utils.tuple_to_schema`
    * and it will return you the subsidies.
    */
    require_once('subsidies.php');
    require_once('utils.php');
    require_once('rules/by_region.php');
    require_once('rules/by_tooth.php');

    // from copy import deepcopy
    // use function lib\vendor\myclabs\deepcopy\src\DeepCopy\deep_copy;

    // $schema = [['18', 'pw'], ['17', ''], ['16', ''], ['15', ''], ['14', 'f'], ['13', ''], ['12', ''], ['11', ''],
    //     ['21', ''], ['22', ''], ['23', ''], ['24', 'ww'], ['25', ''], ['26', ''], ['27', ''], ['28', ''],
    //     ['38', ''], ['37', ''], ['36', ''], ['35', ''], ['34', ''], ['33', ''], ['32', ''], ['31', 'x'],
    //     ['41', ''], ['42', ''], ['43', 'x'], ['44', ''], ['45', ''], ['46', ''], ['47', ''], ['48', '']];

    $schema = ['f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
    tuple_to_schema($schema);
    var_dump(tuple_to_schema($schema));
    generate_all_subsidies(tuple_to_schema($schema));
    function generate_all_subsidies ($schema) {
        /*
        * Generate all subsidy for the given schema.
        */
        // As we need to remove the findings in our evaluation loop,
        // it is better to keep the original schema with no changes
        $schema_by_region = clone($schema);
        $schema_by_tooth = clone($schema);
        $identified_subsidies = new SubsidiesList($schema);
        print_r($identified_subsidies);


        // Get all teeth involved in a rule to remove it from the schema, once
        // we will evaluate the schema recursively without the findings related
        // to the identified rules
        while (evaluate_by_region($schema_by_region, $identified_subsidies)) {
            foreach ($identified_subsidies as $subsidy) {
                // Optional subsidies should not be considered to remove
                // the teeth, it will only be kept as a mark but we could
                // generate other subsidies in the same teeth related to it
                $dependent = array_key_exists('optional', (array) $subsidy) ? $subsidy['optional'] : FALSE;

                // if (! $subsidy.get("optional", False)) {
                if (! $dependent) {
                    print_r($schema_by_region);

                    $schema_by_region->remove_findings($subsidy["region"]);
                }
            }
        }
        
        $subsidies_identified_by_region = sizeof((array)$identified_subsidies);
        print_r('+++++++++++++++++++++++++++++++++++++++++'.$subsidies_identified_by_region);

        while (evaluate_by_tooth($schema_by_tooth, $identified_subsidies)) {
            // We only remove regions of the subsidies identified by_tooth
            foreach ($identified_subsidies[$subsidies_identified_by_region - 1] as $subsidy) {
                // // Optional subsidies should not be considered to remove
                // // the teeth, it will only be kept as a mark but we could
                // // generate other subsidies in the same teeth related to it
                $dependent = array_key_exists('optional', (array) $subsidy) ? $subsidy['optional'] : FALSE;

                // if (! $subsidy.get("optional", False))
                if (! $dependent)
                    $schema_by_tooth->remove_findings($subsidy["region"]);
            }
        }

        print_r($identified_subsidies);
        return $identified_subsidies;
    }